apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: infra
  labels:
    name: db
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: db
  type: NodePort