apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: infra
spec:
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
      restartPolicy: Always