apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: infra
  labels:
    name: app
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    name: app
  type: NodePort
